name: Deploy Backend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: "vjumpkung"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: python -m venv ./venv
      - run: ./venv/bin/python -m pip install -r requirement.txt\
      - run: pm2 restart gened-backend
