name: Deploy Backend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: "vjumpkung"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: python3 -m venv ./venv
      - run: ./venv/bin/python -m pip install -r requirement.txt
      - run: pm2 start ./venv/bin/python -m uvicorn main:app --host 0.0.0.0 --port 3001
